apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app-values-object
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      valuesObject:
        replicaCount: 5
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default