apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana     # specify helm chart name
    targetRevision: 10.5.15
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true